version: "3.8"
services:
  frontend: 
    build: ./company
    container_name: react_container
    ports:
      - '80:3000'
    stdin_open: true
    tty: true

  backend:
    build: .
    container_name: server_container
    ports:
    - '5000:5000'
    volumes:
      - .:/app
