version: "3.8"
services:
  frontend: 
    build: ./datavid-members-client
    container_name: react_container
    ports:
      - '3000:3000'
    stdin_open: true
    tty: true

  backend:
    build: .
    container_name: server_container
    ports:
    - '5000:5000'
    volumes:
      - .:/app
