name: deploy app to aws
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Generate deployment package
        run: zip -r docker-app.zip . -x '*.git*'

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v22
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: Ci-cd-project
          environment_name: Ci-cd-project-env
          existing_bucket_name: elasticbeanstalk-eu-north-1-905418239147
          version_label: ${{ github.sha }}
          region: eu-north-1
          deployment_package: docker-app.zip